// <auto-generated />
namespace TaskTrackingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DevID_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DevID_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "202106030134119_DevID_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
