// <auto-generated />
namespace TaskTrackingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class databaseChanges_v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(databaseChanges_v1));
        
        string IMigrationMetadata.Id
        {
            get { return "202106041912302_databaseChanges_v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
